---
name: proteo
channels:
  - conda-forge
dependencies:
  - python=3.11.*
  - nomkl
  - numpy
  - pip
  - poetry>=1.5.0
  - r-base  # This installs the R language
  - r-essentials  # Includes a collection of commonly used R packages
  - rpy2  # Python to R interface